In [2]:
import numpy as np

In [3]:
a=[1,2,3,4]
type(a)
#list slow processing 
#numpy me fast processing


list

In [5]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [117]:
a=[[2,3,4],
   [4,5,6],
   [7,8,9]]
a

[[2, 3, 4], [4, 5, 6], [7, 8, 9]]

In [17]:
print("total shape",a.shape)
print("total dim ",a.ndim)

total shape (2, 3)
total dim  2


In [11]:
#pre define function in numpy
#(1). zero()==>by this function we can create an array with all values zeros
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [14]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a.ndim

2

In [16]:
a.shape

(2, 3)

In [18]:
#(2)..ones()==>by this function we can create an array all values are one
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [19]:
a.ndim

1

In [21]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a.shape   #shape of array or matrix 

(3, 3)

In [26]:
a.ndim    #dimension calculate 

2

In [29]:
#(3). eye()==>all the dignoal elment are one and other elment  are zero == identical matrix
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [33]:
a=np.eye(4,4)
print(a)
print(a.shape)
print(a.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
2


In [36]:
# (4). diag()==>by this method we can create a array by accoding to user on diagonal element 
a=np.diag([1,2,3,4])
a


(4, 4)

In [38]:
#(5). Random module
#(a) randint()
# a=np.random.randint(min_number,max_num,range)
a=np.random.randint(1,10,3)
a

array([9, 9, 8])

In [60]:
#(b) rand()==> it will generate random number betwween 0 to 1
a=np.random.rand(2,3)
a


array([[0.39534527, 0.35886693, 0.29460915],
       [0.246668  , 0.79772732, 0.70763789]])

In [61]:
a.shape

(2, 3)

In [62]:
a.ndim

2

In [64]:
#reshape by ==>n(rows)xm(col)=total element
a=np.random.randint(1,60,12)
a

array([ 2, 46, 53, 46, 54, 58,  4, 42, 35, 22, 59, 34])

In [65]:
a.shape

(12,)

In [67]:
a=a.reshape(2,6)
a

array([[ 2, 46, 53, 46, 54, 58],
       [ 4, 42, 35, 22, 59, 34]])

In [69]:
a=a.reshape(3,4)
a

array([[ 2, 46, 53, 46],
       [54, 58,  4, 42],
       [35, 22, 59, 34]])

In [70]:
a=a.reshape(4,3)
a

array([[ 2, 46, 53],
       [46, 54, 58],
       [ 4, 42, 35],
       [22, 59, 34]])

In [71]:
a=a.reshape(12,1)
a

array([[ 2],
       [46],
       [53],
       [46],
       [54],
       [58],
       [ 4],
       [42],
       [35],
       [22],
       [59],
       [34]])

In [72]:
a=a.reshape(6,2)
a

array([[ 2, 46],
       [53, 46],
       [54, 58],
       [ 4, 42],
       [35, 22],
       [59, 34]])

In [80]:
a=a.reshape(2,6)
a

array([[ 2, 46, 53, 46, 54, 58],
       [ 4, 42, 35, 22, 59, 34]])

In [81]:
a.shape

(2, 6)

In [86]:
#seed() ==> by this function when the random values cretae at every time seed function fixed the values of randint()
np.random.seed(20)
a=np.random.randint(1,10,3)
a

array([4, 5, 7])

In [116]:
a=[1,2,3]
a=np.random.randint(1,10,3)
a

array([7, 6, 5])

In [109]:
# randn()
a=np.random.randn(15)
a

array([-0.74940461, -0.33974684,  0.82849328,  0.25196816,  1.8719587 ,
       -1.25028393,  0.85966067, -0.52782267,  0.12588876, -1.09030326,
        1.06190893, -0.48307252, -0.9628861 , -0.58119833, -0.31989457])

In [129]:
b=np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

#difference b/t mutable and immutable 
# list and tuple diff
#filter function and map function  and real life use case  of map filter and lambda
#diff b/w strip and split(),isalpha() and isdigit(),isalnum
one example and process